name: Ruby Gem

on:
  workflow_dispatch:

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
        bundler-cache: true

    - name: Set up git config
      run:
        git config user.email "chariderpato@gmail.com"
        git config user.name "patorash"

    - name: Publish to Rubygems
      run : bundle exec rake release
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
